controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_position_example_controller:
      type: franka_example_controllers/JointPositionExampleController

    joint_velocity_example_controller:
      type: franka_example_controllers/JointVelocityExampleController

    joint_impedance_example_controller:
      type: franka_example_controllers/JointImpedanceExampleController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    traj_controller:
      type: joint_trajectory_controller/JointTrajectoryController

traj_controller:
  ros__parameters:
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7
    constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.0
      fr3_joint1: {trajectory: 1.0, goal: 0.01}
      fr3_joint2: {trajectory: 1.0, goal: 0.01}
      fr3_joint3: {trajectory: 1.0, goal: 0.01}
      fr3_joint4: {trajectory: 1.0, goal: 0.01}
      fr3_joint5: {trajectory: 1.0, goal: 0.01}
      fr3_joint6: {trajectory: 1.0, goal: 0.01}
      fr3_joint7: {trajectory: 1.0, goal: 0.01}
    interface_name: position
    state_publish_rate: 25.0
    action_monitor_rate: 10.0
    update_rate: 25
    # max_velocity: 50
    # max_efforts: 1000

joint_position_example_controller:
  ros__parameters:
    gazebo: true

joint_velocity_example_controller:
  ros__parameters:
    gazebo: true
  
joint_impedance_example_controller:
  ros__parameters:
    k_gains:
      - 24.0
      - 24.0
      - 24.0
      - 24.0
      - 10.0
      - 6.0
      - 2.0
    d_gains:
      - 2.0
      - 2.0
      - 2.0
      - 1.0
      - 1.0
      - 1.0
      - 0.5